{
 "title": "Metasploit",
 "description": "Metasploit",
 "tags": [
  "security",
  "metasploit"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Workspace", "query": "SELECT  name FROM workspaces" },
   {
    "name": "Services",
    "label": "Services",
    "query": "SELECT  name FROM services  WHERE state='open'"
   },
   {
    "name": "Hosts",
    "label": "Hosts",
    "query": "SELECT address FROM \"hosts\""
   },
   { "name": "OS", "label": "OS", "query": "SELECT  os_name FROM hosts" }
  ]
 },
 "panels": [
  {
   "title": "Hosts",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "\n<center><h1><strong><u>$Hosts</strong></h1></center>\n\n\n\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT\n  nx_published AS \"time\",\n  cvss_score\nFROM vuln_details\nWHERE\n  $__timeFilter(nx_published)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$Workspace",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n updated_at\nFROM\n \tworkspaces"
    }
   ]
  },
  {
   "title": "Services",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 18, "w": 6, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  updated_at AS \"time\",\n  name AS metric,\n  host_id\nFROM services\nWHERE\n  $__timeFilter(updated_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Open Port",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\ncount (state)\nfrom services\nwhere state = 'open'\ngroup by \"state\""
    }
   ]
  },
  {
   "title": "filtered  Port",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\ncount (state)\nfrom services\nwhere state = 'filtered'\ngroup by \"state\""
    }
   ]
  },
  {
   "title": "filtered  Port",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\ncount (state)\nfrom services\nwhere state = 'unfiltered'\ngroup by \"state\""
    }
   ]
  },
  {
   "title": "Close  Port",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\ncount (state)\nfrom services\nwhere state = 'close'\ngroup by \"state\""
    }
   ]
  },
  {
   "title": "TCP Protocol",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\ncount (proto)\nfrom services\nwhere proto = 'udp'\ngroup by \"proto\" "
    }
   ]
  },
  {
   "title": "TCP Protocol",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\ncount (proto)\nfrom services\nwhere proto = 'tcp'\ngroup by \"proto\""
    }
   ]
  },
  {
   "title": "Info Services",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT state, name FROM services"
    }
   ]
  }
 ]
}